spring.profiles.active=dev
spring.application.name=podcast-episode-release-system
server.port=8083

# Multipart file upload size limits
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
